# Generated by Django 4.2.7 on 2026-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
