# Generated by Django 4.2.7 on 2026-09-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_role_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=True, verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
