# Generated by Django 4.2.7 on 2026-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_chatmessage_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='accident_history',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('unknown', 'Not Sure')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='flood_damage',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('unknown', 'Not Sure')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='modification_status',
            field=models.CharField(blank=True, choices=[('stock', 'Stock / Original'), ('modified', 'Modified')], default='stock', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='previous_owners',
            field=models.CharField(blank=True, choices=[('1', '1 Owner'), ('2', '2 Owners'), ('3', '3 Owners'), ('4+', '4+ Owners'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='price_negotiable',
            field=models.BooleanField(default=False, verbose_name='Price Negotiable'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='reason_for_selling',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='service_records',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=20),
        ),
    ]
